import * as React from "react";
import Head from "next/head";
import { NextPage, GetStaticProps } from "next";
import { getAllFilesFrontMatter } from "lib/mdx";
import Link from "next/link";
import NavBar from "../components/NavBar";
import Slider from "../components/Slider";

const Home = ({ posts }) => {
  const [search, setSearch] = React.useState("");
  const filteredPosts = posts.filter((frontMatter) =>
    frontMatter.title.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="">
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="py-10 shadow-xl">
        <div className="relative ">
          <div className="fixed bg-white w-full py-6 top-0 left-0 right-0">
            <NavBar />
          </div>
        </div>
      </header>
      <div style={{ width: "1wv", margin: "0", zIndex: "-15" }}>
        <Slider />
      </div>
      <main className="py-8 container mx-auto px-44">
        <div className="relative w-full mb-4">
          <input
            type="text"
            aria-label="Search Articles"
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search Articles"
            className="px-4 py-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500   block w-full rounded-md bg-white
             text-gray-900 "
          />
          <svg
            className="absolute right-3 top-3 h-5 w-5 text-gray-400"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
            />
          </svg>
        </div>

        {filteredPosts.map((post) => (
          <Link
            href={`/blog/${post.slug}`}
            key={post.slug}
            className="block rounded border mb-4 border-gray-200 p-4 hover:bg-gray-300"
          >
            {post.title}
          </Link>
        ))}
      </main>

      <footer>
        <a href="/">Hecho Pro salazar dev</a>
      </footer>
    </div>
  );
};

export const getStaticProps = async () => {
  const posts = await getAllFilesFrontMatter("posts");

  return {
    props: { posts },
  };
};

export default Home;
